services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Инициализация Blade в Битриксе.
  symfony_blade.register_bitrix:
    class: Prokl\SymfonyBladeBundle\Services\Providers\BladeProvider
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeProvider', 'register']
    arguments: ['%symfony_blade%']
    tags: ['service.bootstrap']

  # Фабрика View для Битрикса.
  symfony_blade.view_factory:
    class: Illuminate\Contracts\View\Factory
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeProvider', 'getViewFactory']

  # Blade Compiler для Битрикса.
  symfony_blade.compiler:
    class: Prokl\SymfonyBladeBundle\Services\BladeCompilerBitrix
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeProvider', 'getCompiler']

  # Blade для Битрикса.
  symfony_blade.blade:
    class: Prokl\SymfonyBladeBundle\Services\Blade
    arguments:
      - '@symfony_blade.view_factory'
      - ['%symfony_blade.base_path%']

  # Очистка кэша при наличии GET параметра clear_cache.
  symfony_blade.clear_cache:
    class: Prokl\SymfonyBladeBundle\Services\Utils\BladeCacheClearer
    tags:
      - { name: bitrix.events.init, module: main, event: OnProlog, method: clear, sort: 1 }

  # Регистратор кастомных директив для Битрикса.
  symfony_blade.directive_registrator:
    class: Prokl\SymfonyBladeBundle\Services\DirectiveRegistrator
    arguments: ['@symfony_blade.compiler', !tagged blade.custom.directive]
    tags: ['service.bootstrap']
