services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Регистратор кастомных директив для Битрикса.
  symfony_blade.directive_registrator:
    class: Prokl\SymfonyBladeBundle\Services\DirectiveRegistrator
    arguments: ['@symfony_blade.compiler', !tagged blade.custom.directive]
    tags: ['service.bootstrap']

  # Фреймворконезависимый регистратор кастомных директив для Битрикса.
  symfony_blade.directive_registrator_agnostic:
    class: Prokl\SymfonyBladeBundle\Services\DirectiveRegistrator
    arguments: ['@symfony_blade.compiler_agnostic', !tagged blade.custom.directive]
    tags: ['service.bootstrap']

  ############
  # Директивы
  ###########

  # Логические директивы.
  Prokl\SymfonyBladeBundle\Services\Directives\BladeIsDirectives:
    class: Prokl\SymfonyBladeBundle\Services\Directives\BladeIsDirectives
    tags:
      - { name: blade.custom.directive }

  # Отладочные директивы.
  Prokl\SymfonyBladeBundle\Services\Directives\BladeDebugDirectives:
    class: Prokl\SymfonyBladeBundle\Services\Directives\BladeDebugDirectives
    tags:
      - { name: blade.custom.directive }
