services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Prokl\SymfonyBladeBundle\Services\Filters\FiltersRegistrator:
    class: Prokl\SymfonyBladeBundle\Services\Filters\FiltersRegistrator
    arguments: [!tagged blade.custom.filter]

  ##########
  # Фильтры
  ##########

  # Строковые фильтры.
  Prokl\SymfonyBladeBundle\Services\Filters\Filters\BladeStringFilters:
    class: Prokl\SymfonyBladeBundle\Services\Filters\Filters\BladeStringFilters
    tags:
      - { name: blade.custom.filter }

