services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Фреймворконезависимая инициализация Blade.
  symfony_blade.register_agnostic:
    class: Prokl\SymfonyBladeBundle\Services\Providers\BladeAgnosticProvider
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeAgnosticProvider', 'register']
    arguments: ['%symfony_blade%']
    tags: ['service.bootstrap']

  # Фреймворконезависимая фабрика View.
  symfony_blade.view_factory_agnostic:
    class: Illuminate\Contracts\View\Factory
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeAgnosticProvider', 'getViewFactory']

  # Фреймворконезависимый Blade Compiler.
  symfony_blade.compiler_agnostic:
    class: Illuminate\View\Compilers\BladeCompiler
    factory: ['Prokl\SymfonyBladeBundle\Services\Providers\BladeAgnosticProvider', 'getCompiler']

  # Фреймворконезависимый Blade.
  symfony_blade.blade_instance:
    class: Prokl\SymfonyBladeBundle\Services\Blade
    arguments:
      - '@symfony_blade.view_factory_agnostic'
      - ['%symfony_blade.base_path%']
